FROM debian

RUN apt-get update && apt-get upgrade -y && \
	apt-get install -y vim net-tools nmap

# a basic local network scanning environment

# docker build -t b01 .
# docker run -it --rm b01

# nmap 192.168.99.100
# exit