## Debian with C dev environment
FROM debian

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y build-essential git vim

# To build and run:
# docker build -t b02 .
# docker run -it --rm b02
