FROM alpine

RUN apk update \
	&& apk upgrade \
	&& apk add vim

CMD ["vim"]

# docker build -t ex00
# docker build -t ex00 ex00/  if you're building from outside this folder
# docker run -it --rm ex00
